---
name: Build and push Docker image

on:
  push:
    branches:
      - 'master'
jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    if: (contains(github.event.head_commit.message, '[skip ci]') == false) && (github.event_name == 'push')
    steps:
      - uses: actions/checkout@v2

      - name: Generate Makefile
        run: ./configure

      - name: Build image
        run: make dockerbuild 
        env: 
          BASE_IMAGE: nodejs:12.19.0-alpine3.11
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: make dockerpush

